name: CI
on: push

jobs:
    build:
     runs-on: ubuntu-latest
     steps:
     - name: descargar repostorio
       uses: actions/checkout@v3
     - name: pruebas-unitarias
       run: mvn test
     - name: compilar la aplicación sin repetir pruebas
       run: mvn package -DskipTests=true
    test:
      needs: build
      runs-on: self-hosted 
      steps: 
      - name: pruebas-funcionales 
        run: echo "pruebas-funcionales" 
      - name: instalar aplicación en Tomcat
        run: |
          mvn package -DskipTests=true
          cp -r target/Baloncesto /usr/local/tomcat/webapps
      - name: preparar base de datos de prueba
        run: |
          mysql -u root < db/baloncesto.sql
          export DATABASE_HOST="jdbc:mysql://localhost"
          export DATABASE_PORT="3306"´
          export DATABASE_NAME="baloncesto"
          export DATABASE_USER="usuario"
          export DATABASE_USER="usuario"
          sh /usr/local/tomcat/bin/catalina.sh stop
          sh /usr/local/tomcat/bin/catalina.sh start
      - name: realizar pruebas funcionales
        run: |
          mvn failsafe:integration-test failsafe:verify
    qa:
      needs: test
      runs-on: self-hosted 
      steps: 
      - name: calidad-codigo 
        run: echo "calidad-codigo" 
    stage:
      needs: qa
      runs-on: ubuntu-latest
      steps:
      - name: pre-producción
        run: echo "pre"
    deploy:
      needs: stage
      runs-on: ubuntu-latest 
      steps: 
      - name: despliegue 
        run: echo "despliegue"
  
