name: CI
on: push

jobs:
    build:
     runs-on: ubuntu-latest
     steps:
     - name: descargar repostorio
       uses: actions/checkout@v3
     - name: pruebas-unitarias
       run: mvn test
     - name: compilar la aplicación sin repetir pruebas
       run: mvn package 
    test:
      needs: build
      runs-on: self-hosted 
      steps: 
      - name: pruebas-funcionales 
        run: echo "pruebas-funcionales" 

    qa:
      needs: test
      runs-on: self-hosted 
      steps: 
      - name: calidad-codigo 
        run: echo "calidad-codigo" 
    stage:
      needs: qa
      runs-on: ubuntu-latest
      steps:
      - name: pre-producción
        run: echo "pre"
    deploy:
      needs: stage
      runs-on: ubuntu-latest 
      steps: 
      - name: despliegue 
        run: echo "despliegue"
  
