name: CI
on: push

jobs:
    build:
     runs-on: ubuntu-latest
     steps:
     - name: descargar repostorio
       uses: actions/checkout@v3
     - name: pruebas-unitarias
       run: mvn test
     - name: compilar la aplicación sin repetir pruebas
       run: mvn package -DskipTests=true
    test:
      needs: build
      runs-on: self-hosted 
      steps: 
      - name: descargar repostorio
        uses: actions/checkout@v3
      - name: instalar aplicación en Tomcat
        run: |
          mvn package -DskipTests=true
          cp -r target/Baloncesto /usr/local/tomcat/webapps
      - name: preparar base de datos de prueba
        run: |
          mysql -u root < db/baloncesto.sql
          export DATABASE_HOST="jdbc:mysql://localhost"
          export DATABASE_PORT="3306"´
          export DATABASE_NAME="baloncesto"
          export DATABASE_USER="usuario"
          export DATABASE_USER="usuario"
          sh /usr/local/tomcat/bin/catalina.sh stop
          sh /usr/local/tomcat/bin/catalina.sh start
      - name: realizar pruebas funcionales
        run: |
          mvn failsafe:integration-test failsafe:verify
    qa:
      needs: test
      runs-on: self-hosted 
      continue-on-error: true
      steps: 
      - name: calidad-codigo 
        run: |
          mvn sonar:sonar -Dsonar.host.url=http://sonarqube:9000 -Dsonar.qualitygate.wait=true -Dsonar.login=admin -Dsonar.password=1234
    stage:
      runs-on: ubuntu-latest
      needs: qa
      if: github.ref == 'refs/heads/pre-produccion'
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Crear el archivo .war
        run: |
          mvn package -DskipTests=true
      - name: Desplegar en Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: pre-baloncesto-calzada-maldonado
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/*.war
    deploy:
      runs-on: ubuntu-latest
      needs: stage
      if: github.ref == 'refs/heads/main'
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
        - name: Crear el archivo .war
          run: |
            mvn package -DskipTests=true
        - name: Aprobación manual
          uses: trstringer/manual-approval@v1
          with:
            secret: ${{ secrets.TOKEN }}
            approvers: raulCalzada
        - name: Desplegar en Azure
          uses: Azure/webapps-deploy@v2
          with:
            app-name: baloncesto-calzada-maldonado
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            package: target/*.war
  
